RSquad/ton-teleport-btc-periphery

lib/pkg/logger/logger.go, oracle/README.md, oracle/cmd/main.go, oracle/internal/cfg/cfg.go, oracle/internal/dkg/dkg_executor.go, oracle/internal/dkg/dkg_executor_feedback.go, oracle/internal/signing/service.go
- Add log configuration attributes to config
- Add validator index to logout
=> Add log configuration attributes to config

lib/pkg/ton/coordinator/getters.go, lib/pkg/ton/coordinator/types.go, oracle/internal/helpers.go, oracle/internal/signing/logging.go, oracle/internal/signing/service.go
- add log message for error code 171
- upd error log for sendSigningShare and sendSignatures
=> feat: fix GetUnsignedPegouts method

grafana/dashboards/advanced.json, grafana/dashboards/internal-keys.json, grafana/dashboards/operations.json, grafana/dashboards/statistics.json
=> Fix dashboard api url

oracle/internal/dkg/dkg_executor.go, oracle/internal/dkg/dkg_executor_test.go
Fix TOB-TGBTC-19
https://rsquad-blockchain-lab.atlassian.net/browse/TTBTC-482
=> Fix TOB-TGBTC-19

lib/pkg/ton/coordinator/coordinator_contract.go, lib/pkg/ton/coordinator/msgs.go, lib/pkg/ton/coordinator/msgs_test.go, lib/pkg/ton/coordinator/operations.go, oracle/internal/dkg/dkg_executor.go
feat(lib, oracle): sign message body (part3 opcode) with the session key to avoid session public keys duplication
=> TOB-TGBTC-18

oracle/internal/dkg/dkg_crypto.go, oracle/internal/dkg/dkg_crypto_test.go, oracle/internal/dkg/dkg_executor.go, oracle/internal/helpers.go
=> Fix TOB-TGBTC-20

oracle/internal/dkg/dkg_executor.go, oracle/internal/helpers.go, oracle/internal/helpers_test.go
Fixed the deserialization of the DkgR2 package (TOB-TGBTC-17)
=> Fixed the deserialization of the DkgR2 package (TOB-TGBTC-17)

oracle/internal/keystore/keystore.go, oracle/internal/keystore/keystore_test.go
Implement folder flag permission verification (TOB-TGBTC-12)
=> Implement folder flag permission verification (TOB-TGBTC-12)

oracle/internal/signing/service.go, oracle/internal/signing/service_test.go
* feat(oracle): regenerate nonces & commitments on every pegout restart
=> TOB-TGBTC-30 

lib/pkg/utils/bytes.go, lib/pkg/utils/bytes_test.go
=> Fix TOB-TGBTC-31

oracle/internal/dkg/dkg_crypto.go, oracle/internal/helpers.go
Task: https://rsquad-blockchain-lab.atlassian.net/browse/TTBTC-610
=> Make map iteration deterministic for accurate culprit detection

oracle/internal/dkg/dkg_service.go, oracle/internal/helpers.go, oracle/internal/signing/logging.go, oracle/internal/signing/service.go
Task: https://rsquad-blockchain-lab.atlassian.net/browse/TTBTC-649
=> Implement index boundary checks and improve log messages

oracle/internal/dkg/dkg_executor.go, oracle/internal/dkg/dkg_executor_feedback.go, oracle/internal/helpers.go, oracle/internal/signing/logging.go, oracle/internal/signing/service.go
https://rsquad-blockchain-lab.atlassian.net/browse/TTBTC-688
Update log messages
=> Update log messages

lib/pkg/ton/coordinator/getters.go, lib/pkg/ton/coordinator/getters_test.go
- fixed dict loading in loadSharesMap: ToDict instead of MustLoadDict
- added unit tests for loadSharesMap
=> fix(lib): fix loadSharesMap func

frost/frost.go, indexer/README.md, indexer/cmd/main.go, indexer/internal/config/config.go, indexer/internal/config/services_config.go, indexer/internal/gql/ent_resolvers.go, indexer/internal/metrics/fetcher_contract_balances.go, indexer/internal/metrics/fetcher_dkg.go, indexer/internal/metrics/json_api_handler.go, indexer/internal/metrics/metrics_service.go, indexer/internal/tontx/ton_tx_writer.go, lib/pkg/ton/coordinator/getters.go, lib/pkg/ton/coordinator/types.go, oracle/cmd/main.go, oracle/internal/signing/logging.go, oracle/internal/signing/service.go, oracle/oracle_instructions.md
* Oracle frost test build bugfix
* Update Indexer config and documentation
* Add default TON config
=> Oracle bugfix, indexer config update

indexer/internal/metrics/json_api_handler.go
fix `amount` value type in SQL query for dashboards
=> fix value type in SQL query for dashboards

relayer/internal/pegout_relayer/pegout_relayer.go
Refactor PegoutRelayer logic to simplify confirmation checks by removing unnecessary confirmation retrieval. (#254)
=> fix(relayer): fix pegout confirmation

grafana/dashboards/advanced.json, grafana/dashboards/burns.json, grafana/dashboards/internal-keys.json, grafana/dashboards/mints.json, grafana/dashboards/operations.json, grafana/dashboards/reinits.json, grafana/dashboards/statistics.json
=> Fix dashboards API url

metrics/README.md, metrics/cmd/main.go, metrics/internal/config/config.go, metrics/internal/config/services_config.go, metrics/internal/httpservice/http_service.go
=> Add HTTP port to config

metrics/internal/data_sources/data_source_db.go, metrics/internal/metrics/mertics_manager.go
=> fix API metrics call result

metrics/internal/alerts/alert_pegout_in_mempool.go, metrics/internal/fetchers/fetcher_bitcoin_network.go, metrics/internal/fetchers/fetcher_contract_balance.go, metrics/internal/fetchers/fetcher_contract_bitcoin_client.go, metrics/internal/fetchers/fetcher_contract_coordinator.go, metrics/internal/metrics/mertics_manager.go
* fix alert_pegout_in_mempoo
* Bugfix
=> fix alert_pegout_in_mempool (#302)

oracle/oracle_instructions.md
Update Oracle instructions. Add "Oracle Check-list After Upgrade" part
=> Update Oracle instructions

oracle/oracle_instructions.md
* Update Oracle instructions
* Enhance Oracle instructions with post-upgrade verification checklist
* add env var checklist
---------
=> Update Oracle instructions (#310)

metrics/internal/alerts/alert_dkg_participants.go, metrics/internal/alerts/alert_dkg_participants_test.go
Add participant count to alert_dkg_participants labels
=> Add participant count to alert_dkg_participants labels

metrics/telegram.tmpl
=> Update alert messages
